version: "3"
services:
  taskmanager:
    build:
      context: .
      dockerfile: ./container/Dockerfile
    container_name: taskmanager
    volumes:
      - .:/var/www/app
      - ./container/apache.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - 3000:80